SolverTest Class Reference
Google Test fixture for testing various solver classes.
Protected Member Functions
void ReadTestFile (const std::string &fileName, const std::string &content)
Helper function to read and parse a temporary test file.
Protected Attributes
Input input
Instance of Input for testing solvers.
Detailed Description
Google Test fixture for testing various solver classes.
Member Function Documentation
ReadTestFile()
void SolverTest::ReadTestFile (const std::string & fileName, const std::string & content) [inline], [protected]
Helper function to read and parse a temporary test file.
Parameters
fileName Name of the file to read.
content Content to write to the file.
References CleanUpTempFile(), input, Input::ReadFile(), and WriteToTempFile().
Member Data Documentation
input
Input SolverTest::input [protected]
Instance of Input for testing solvers.
The documentation for this class was generated from the following file:
test/test.cpp