InputTest Class Reference
Google Test fixture for testing the Input class.
Protected Member Functions
void ReadTestFile (const std::string &fileName, const std::string &content)
Helper function to read and parse a temporary test file.
Protected Attributes
Input input
Instance of Input for testing.
Detailed Description
Google Test fixture for testing the Input class.
Provides helper methods for reading test files and cleaning up temporary data.
Member Function Documentation
ReadTestFile()
void InputTest::ReadTestFile (const std::string & fileName, const std::string & content) [inline], [protected]
Helper function to read and parse a temporary test file.
Parameters
fileName Name of the file to read.
content Content to write to the file.
References CleanUpTempFile(), input, Input::ReadFile(), and WriteToTempFile().
Member Data Documentation
input
Input InputTest::input [protected]
Instance of Input for testing.
The documentation for this class was generated from the following file:
test/test.cpp