test/test.cpp File Reference
#include <gtest/gtest.h>
#include <fstream>
#include `../src/input.hpp`
#include `../src/solver.hpp`
Classes
class InputTest
Google Test fixture for testing the Input class.
class SolverTest
Google Test fixture for testing various solver classes.
Functions
void WriteToTempFile (const std::string &fileName, const std::string &content)
Creates and writes content to a temporary file.
void CleanUpTempFile (const std::string &fileName)
Deletes a temporary file.
TEST_F (InputTest, ParsesValidRealMatrix)
Validates parsing a real matrix from input.
TEST_F (InputTest, ParsesValidComplexMatrix)
Validates parsing a complex matrix from input.
TEST_F (InputTest, ThrowsForInvalidMatrixDimensions)
Validates exception is thrown for invalid matrix dimensions.
TEST_F (InputTest, ThrowsForInvalidMethod)
Validates exception is thrown for invalid METHOD parameter.
TEST_F (InputTest, ParsesSingularMatrix)
Validates parsing a singular matrix from input.
TEST_F (InputTest, ThrowsForMissingMatrixData)
Validates exception is thrown when MATRIX_DATA is missing.
TEST_F (SolverTest, PowerMethodSolverRealMatrix)
Validates the Power Method solver with a real matrix.
TEST_F (SolverTest, InversePowerMethodSolverRealMatrix)
Validates the Inverse Power Method solver with a real matrix.
TEST_F (SolverTest, QRMethodSolverRealMatrix)
Validates the QR Method solver with a real matrix.
TEST_F (SolverTest, PowerMethodSolverComplexMatrix)
Validates the Power Method solver with a complex matrix.
TEST_F (SolverTest, QRMethodSolverComplexMatrix)
Validates the QR Method solver with a complex matrix.
void RunSolverAndThrow (Input &input)
Executes the Inverse Power Method Solver and propagates exceptions.
TEST_F (SolverTest, InversePowerMethodSolverSingularRealMatrixThrows)
Validates exception handling for singular real matrices in the Inverse Power Method solver.
TEST_F (SolverTest, InversePowerMethodSolverSingularRealMatrixThrowsWithShift)
Validates exception handling for singular real matrices in the Inverse Power Method solver with a non-zero shift.
TEST_F (SolverTest, QRConvergenceTest)
Validates the QR Method solver's convergence for a simple real matrix.
Function Documentation
CleanUpTempFile()
void CleanUpTempFile (const std::string & fileName)
Deletes a temporary file.
Parameters
fileName Name of the file to delete.
RunSolverAndThrow()
void RunSolverAndThrow (Input & input)
Executes the Inverse Power Method Solver and propagates exceptions.
This function is designed to test scenarios where the solver is expected to fail (or not)due to invalid input (e.g., singular matrices). It is used to test the difference between singular matrices and the case where the file doesn't converge .
Parameters
input An instance of the Input class containing solver configuration.
Exceptions
std::runtime_error If the solver encounters an issue during execution.
References InversePowerMethodSolver< MatrixType, T >::solve().
TEST_F() [1/14]
TEST_F (InputTest , ParsesSingularMatrix)
Validates parsing a singular matrix from input.
Test
Test InputTest::ParsesSingularMatrix
TEST_F() [2/14]
TEST_F (InputTest , ParsesValidComplexMatrix)
Validates parsing a complex matrix from input.
Test
Test InputTest::ParsesValidComplexMatrix
TEST_F() [3/14]
TEST_F (InputTest , ParsesValidRealMatrix)
Validates parsing a real matrix from input.
Test
Test InputTest::ParsesValidRealMatrix
TEST_F() [4/14]
TEST_F (InputTest , ThrowsForInvalidMatrixDimensions)
Validates exception is thrown for invalid matrix dimensions.
Test
Test InputTest::ThrowsForInvalidMatrixDimensions
TEST_F() [5/14]
TEST_F (InputTest , ThrowsForInvalidMethod)
Validates exception is thrown for invalid METHOD parameter.
Test
Test InputTest::ThrowsForInvalidMethod
TEST_F() [6/14]
TEST_F (InputTest , ThrowsForMissingMatrixData)
Validates exception is thrown when MATRIX_DATA is missing.
Test
Test InputTest::ThrowsForMissingMatrixData
TEST_F() [7/14]
TEST_F (SolverTest , InversePowerMethodSolverRealMatrix)
Validates the Inverse Power Method solver with a real matrix.
Test
Test SolverTest::InversePowerMethodSolverRealMatrix
Tests that the solver computes the eigenvalue closest to a given shift. < Eigenvalue closest to shift
References InversePowerMethodSolver< MatrixType, T >::solve().
TEST_F() [8/14]
TEST_F (SolverTest , InversePowerMethodSolverSingularRealMatrixThrows)
Validates exception handling for singular real matrices in the Inverse Power Method solver.
Test
Test SolverTest::InversePowerMethodSolverSingularRealMatrixThrows
Tests that the solver throws a runtime error when solving a singular matrix with a shift of 0.
References RunSolverAndThrow().
TEST_F() [9/14]
TEST_F (SolverTest , InversePowerMethodSolverSingularRealMatrixThrowsWithShift)
Validates exception handling for singular real matrices in the Inverse Power Method solver with a non-zero shift.
Test
Test SolverTest::InversePowerMethodSolverSingularRealMatrixThrowsWithShift
Ensures the solver throws a runtime error even when a shift (e.g., 2.0) is applied.
References RunSolverAndThrow().
TEST_F() [10/14]
TEST_F (SolverTest , PowerMethodSolverComplexMatrix)
Validates the Power Method solver with a complex matrix.
Test
Test SolverTest::PowerMethodSolverComplexMatrix
Ensures the solver correctly computes the largest eigenvalue with both real and imaginary parts. < Real part of the largest eigenvalue.
< Imaginary part of the largest eigenvalue.
References PowerMethodSolver< MatrixType, T >::solve().
TEST_F() [11/14]
TEST_F (SolverTest , PowerMethodSolverRealMatrix)
Validates the Power Method solver with a real matrix.
Test
Test SolverTest::PowerMethodSolverRealMatrix
Tests that the solver correctly computes the largest eigenvalue. < Largest eigenvalue
References PowerMethodSolver< MatrixType, T >::solve().
TEST_F() [12/14]
TEST_F (SolverTest , QRConvergenceTest)
Validates the QR Method solver's convergence for a simple real matrix.
Test
Test SolverTest::QRConvergenceTest
Ensures the solver runs without throwing any errors when handling a non-singular matrix.
References RunSolverAndThrow().
TEST_F() [13/14]
TEST_F (SolverTest , QRMethodSolverComplexMatrix)
Validates the QR Method solver with a complex matrix.
Test
Test SolverTest::QRMethodSolverComplexMatrix
Ensures the solver computes all eigenvalues accurately. < Ensure correct result size.
References QRMethodSolver< MatrixType, T >::solve().
TEST_F() [14/14]
TEST_F (SolverTest , QRMethodSolverRealMatrix)
Validates the QR Method solver with a real matrix.
Test
Test SolverTest::QRMethodSolverRealMatrix
Ensures the solver computes all eigenvalues accurately. < Ensure correct result size.
< Largest eigenvalue.
< Middle eigenvalue.
< Smallest eigenvalue.
References QRMethodSolver< MatrixType, T >::solve().
WriteToTempFile()
void WriteToTempFile (const std::string & fileName, const std::string & content)
Creates and writes content to a temporary file.
Parameters
fileName Name of the file to create.
content Content to write to the file.
Exceptions
std::runtime_error If the file cannot be created.