Output Class Reference
Handles formatted output of eigenvalue solver results.
#include <output.hpp>
Public Member Functions
Output (std::string fileName=`output.txt`)
Constructor.
void PrintHeader (const std::string &title)
Displays a styled header.
template<typename T >
void WriteEigenvalue (const T &eigenvalue, const std::string &method)
Writes eigenvalues.
void WriteSummary (const Input &inputFile)
Writes a summary of the input parameters.
void DisplayError (const std::string &message)
Displays error messages.
void WriteToFile (const std::string &message)
Appends messages to the output file.
void SaveToFile () const
Saves the output to the specified file.
void Clear ()
Clears the output buffer.
void OpenFile () const
Opens the output file with the system's default application.
Detailed Description
Handles formatted output of eigenvalue solver results.
The Output class provides functionality to display and save results of eigenvalue solvers. It includes methods for:
Displaying headers and results in a styled format on the console.
Writing results and errors to a file.
Managing formatted output for real and complex eigenvalues.
Note
ANSI escape codes are used for terminal styling, which may not be supported in all environments.
Constructor & Destructor Documentation
Output()
Output::Output (std::string fileName = `output.txt`) [inline], [explicit]
Constructor.
Member Function Documentation
Clear()
void Output::Clear () [inline]
Clears the output buffer.
DisplayError()
void Output::DisplayError (const std::string & message) [inline]
Displays error messages.
Displays an error message in a styled format on the console and logs it to the output file.
Parameters
message The error message to display in the terminal and log in the output file.
References BOLD, centerText(), RED, and RESET.
OpenFile()
void Output::OpenFile () const [inline]
Opens the output file with the system's default application.
Opens the output file.
PrintHeader()
void Output::PrintHeader (const std::string & title) [inline]
Displays a styled header.
Displays a styled header with a title.
Parameters
title The title to display.
References BOLD, centerText(), MAGENTA, and RESET.
SaveToFile()
void Output::SaveToFile () const [inline]
Saves the output to the specified file.
Writes eigenvalue(s) to both the terminal and the output file.
Template Parameters
T The type of eigenvalue (scalar, complex, or vector).
/**
Saves the collected output to the specified file.
WriteEigenvalue()
template<typename T >
void Output::WriteEigenvalue (const T & eigenvalue, const std::string & method)
Writes eigenvalues.
Writes eigenvalue(s) to both the terminal and the output file.
Template Parameters
T The type of eigenvalue (scalar, complex, or vector).
Parameters
eigenvalue The computed eigenvalue(s).
method The name of the method used to compute the eigenvalue(s).
References centerText(), complexToString(), CYAN, and RESET.
WriteSummary()
void Output::WriteSummary (const Input & inputFile) [inline]
Writes a summary of the input parameters.
Writes a summary of input parameters to the output.
References centerText(), Input::GetComplexMatrix(), Input::GetDimension(), Input::GetIsComplex(), Input::GetMaxIter(), Input::GetMethod(), Input::GetRealMatrix(), Input::GetShift(), Input::GetTolerance(), MAGENTA, and RESET.
WriteToFile()
void Output::WriteToFile (const std::string & message) [inline]
Appends messages to the output file.
Logs a message to the output file, including eigenvalues or error details.
Parameters
message The message to log in the output file.
The documentation for this class was generated from the following files:
src/output.hpp
src/output_imp.hpp