
% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Cl", "Cd"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DP2421T = readtable(".\DP2421T.csv", opts);
DP2418T = readtable(".\DP2418T.csv", opts);
DP2415T = readtable(".\DP2415T.csv", opts);
DP2412T = readtable(".\DP2412T.csv", opts);
DP2409T = readtable(".\DP2409T.csv", opts);
DP2406T = readtable(".\DP2406T.csv", opts);
DP2421 = readtable(".\DP2421.csv", opts);
DP2418 = readtable(".\DP2418.csv", opts);
DP2415 = readtable(".\DP2415.csv", opts);
DP2412 = readtable(".\DP2412.csv", opts);
DP2409 = readtable(".\DP2409.csv", opts);
DP2406 = readtable(".\DP2406.csv", opts);
%Clear temporary variables
clear opts

%% Import data from text file LC2412
% Script for importing data from the following text file:
%
%    filename: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\LC2412.csv
%
% Auto-generated by MATLAB on 01-Nov-2023 17:44:40

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alpha", "Cl_a"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LC2421T = readtable(".\LC2421T.csv", opts);
LC2418T = readtable(".\LC2418T.csv", opts);
LC2415T = readtable(".\LC2415T.csv", opts);
LC2412T = readtable(".\LC2412T.csv", opts);
LC2409T = readtable(".\LC2409T.csv", opts);
LC2406T = readtable(".\LC2406T.csv", opts);
LC2421 = readtable(".\LC2421.csv", opts);
LC2418 = readtable(".\LC2418.csv", opts);
LC2415 = readtable(".\LC2415.csv", opts);
LC2412 = readtable(".\LC2412.csv", opts);
LC2409 = readtable(".\LC2409.csv", opts);
LC2406 = readtable(".\LC2406.csv", opts);
% Clear temporary variables
clear opts

%% Import data from spreadsheet EXP
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\Experimental Data.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 01-Nov-2023 18:47:55

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:AC30";

% Specify column names and types
opts.VariableNames = ["Alpha", "NACA2406", "NACA2406D", "NACA2406tripped", "NACA2406trippedD", "NACA2409", "NACA2409D", "NACA2409tripped", "NACA2409trippedD", "NACA2412", "NACA2412D", "NACA2412tripped", "NACA2412trippedD", "NACA2415", "NACA2415D", "NACA2415tripped", "NACA2415trippedD", "NACA2418", "NACA2418D", "NACA2418tripped", "NACA2418trippedD", "NACA2421", "NACA2421D", "NACA2421tripped", "NACA2421trippedD", "NACA1412", "NACA1412D", "NACA3412", "NACA3412D"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ExperimentalData = readtable(".\Experimental Data.xlsx", opts, "UseExcel", false);

%Clear temporary variables
clear opts

%% Plots NUM
%Lift curve
Alpha = LC2406T.Alpha;
Cl_a = LC2406T.Cl_a;
figure()
plot (Alpha,Cl_a,'LineWidth',1.5)
hold on;
xticks(-20:10:20);
yticks(-2:0.5:2.5);
title('Lift curve : NUM Thickness Analysis T');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
%2409
Alpha = LC2409T.Alpha;
Cl_a = LC2409T.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2412
Alpha = LC2412T.Alpha;
Cl_a = LC2412T.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2415
Alpha = LC2415T.Alpha;
Cl_a = LC2415T.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2418
Alpha = LC2418T.Alpha;
Cl_a = LC2418T.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2421
Alpha = LC2421T.Alpha;
Cl_a = LC2421T.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
legend('2406T','','', '2409T', '2412T', '2415T', '2418T', '2421T', 'Location', 'southeast')
hold off

%Drag Polar
figure()
Cl=DP2406T.Cl;
Cd=DP2406T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):0.5:xL(2));
yticks(yL(1):0.02:yL(2));
title('Drag polar : NUM Thickness Anaysis T');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);   %y-axis 
%2409
Cl=DP2409T.Cl;
Cd=DP2409T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2412
Cl=DP2412T.Cl;
Cd=DP2412T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2415
Cl=DP2415T.Cl;
Cd=DP2415T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2418
Cl=DP2418T.Cl;
Cd=DP2418T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2421
Cl=DP2421T.Cl;
Cd=DP2421T.Cd;
plot (Cl,Cd,'LineWidth',1.5)
legend('2406T','', '2409T', '2412T', '2415T', '2418T', '2421T')
hold off;

%% Plots EXP
%Lift Curve
Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2406tripped)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Alpha,Cl_a,'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):10:xL(2));
yticks(-1:0.5:1.5);
title('Lift curve : EXP Thickness Analysis T ');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_L');
yline(0, 'k','LineStyle','--','LineWidth',0.25);  %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis


Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2409tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2412tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2415tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2418tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2421tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)
hold off; 
legend('2406T','','', '2409T', '2412T', '2415T', '2418T', '2421T', 'Location', 'southeast')

%Drag Polar
Cl=(ExperimentalData.NACA2406tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2406trippedD)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Cl,Cd,'LineWidth',1.5)
hold on;
yL = ylim;
xticks(-1:0.5:1.5);
yticks(yL(1):0.04:0.36);
title('Drag polar : EXP Thickness Analysis T');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis

Cl=(ExperimentalData.NACA2409tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2409trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2412tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2412trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2415tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2415trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2418tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2418trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2421tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2421trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)
legend('2406T','', '2409T', '2412T', '2415T', '2418T', '2421T')
hold off;
%% TRIPPED VS LAMINAR 
%% Plots NUM
%DRAG POLAR 
figure()
Cl=DP2409.Cl;
Cd=DP2409.Cd;
plot (Cl,Cd,'Color',"#4DBEEE",'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):0.5:xL(2));
yticks(yL(1):0.02:yL(2));
title('Drag polar : NUM Normal vs Tripped Flow');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);   %y-axis 
%2409T
Cl=DP2409T.Cl;
Cd=DP2409T.Cd;
plot (Cl,Cd,'Color',"#0072BD",'LineWidth',1.5)
%2415
Cl=DP2415.Cl;
Cd=DP2415.Cd;
plot (Cl,Cd,'Color',"#D95319",'LineWidth',1.5 )
%2415T
Cl=DP2415T.Cl;
Cd=DP2415T.Cd;
plot (Cl,Cd,'Color',"#A2142F",'LineWidth',1.5)
%2421
Cl=DP2421.Cl;
Cd=DP2421.Cd;
plot (Cl,Cd,'Color', 'g','LineWidth',1.5)
%2421T
Cl=DP2421T.Cl;
Cd=DP2421T.Cd;
plot (Cl,Cd,'Color', "#77AC30",'LineWidth',1.5)
legend('2409','', '2409T', '2415', '2415T', '2421', '2421T')
hold off

%Lift curve
Alpha = LC2409.Alpha;
Cl_a = LC2409.Cl_a;
figure()
plot (Alpha,Cl_a,'Color',"#4DBEEE",'LineWidth',1.5)
hold on;
xticks(-20:10:20);
yticks(-2:0.5:2.5);
title('Lift curve : NUM Normal vs Tripped Flow');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
%2409T
Alpha = LC2409T.Alpha;
Cl_a = LC2409T.Cl_a;
plot (Alpha,Cl_a,'Color',"#0072BD",'LineWidth',1.5)
%2415
Alpha = LC2415.Alpha;
Cl_a = LC2415.Cl_a;
plot (Alpha,Cl_a,'Color',"#D95319",'LineWidth',1.5)
%2415T
Alpha = LC2415T.Alpha;
Cl_a = LC2415T.Cl_a;
plot (Alpha,Cl_a,'Color',"#A2142F",'LineWidth',1.5)
%2421
Alpha = LC2421.Alpha;
Cl_a = LC2421.Cl_a;
plot (Alpha,Cl_a,'g','LineWidth',1.5)
%2421T
Alpha = LC2421T.Alpha;
Cl_a = LC2421T.Cl_a;
plot (Alpha,Cl_a,'Color', "#77AC30",'LineWidth',1.5)
legend('2409','','', '2409T', '2415', '2415T', '2421', '2421T', 'Location', 'southeast')
hold off
%% EXP plot 
Cl=(ExperimentalData.NACA2409)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2409D)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Cl,Cd,'Color',"#4DBEEE",'LineWidth',1.5)
hold on;
yL = ylim;
xticks(-1:0.5:1.5);
yticks(yL(1):0.04:0.36);
title('Drag polar : EXP Normal vs Tripped Flow');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis

Cl=(ExperimentalData.NACA2409tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2409trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'Color',"#0072BD",'LineWidth',1.5)

Cl=(ExperimentalData.NACA2415)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2415D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'Color',"#D95319",'LineWidth',1.5 )

Cl=(ExperimentalData.NACA2415tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2415trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'Color',"#A2142F",'LineWidth',1.5)

Cl=(ExperimentalData.NACA2421)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2421D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'Color', 'g','LineWidth',1.5)

Cl=(ExperimentalData.NACA2421tripped)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2421trippedD)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'Color', "#77AC30",'LineWidth',1.5)
legend('2409','', '2409T', '2415', '2415T', '2421', '2421T')
hold off
%Lift Curve
Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2409)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Alpha,Cl_a,'Color',"#4DBEEE",'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):10:xL(2));
yticks(-1:0.5:1.5);
title('Lift curve : EXP Normal vs Tripped Flow ');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_L');
yline(0, 'k','LineStyle','--','LineWidth',0.25);  %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis


Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2409tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'Color',"#0072BD",'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2415)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'Color',"#D95319",'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2415tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'Color',"#A2142F",'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2421)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'g','LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2421tripped)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'Color', "#77AC30",'LineWidth',1.5)
legend('2409','','', '2409T', '2415', '2415T', '2421', '2421T', 'Location', 'southeast')
hold off