%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\W2412LC.csv
%
% Auto-generated by MATLAB on 13-Nov-2023 22:13:38

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alpha", "Cl"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
W2412LC = readtable(".\W2412LC.csv", opts);

clear opts
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alpha", "Cd"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
W2412DC = readtable(".\W2412DC.csv", opts);

clear opts

%Lift Curve
Alpha = W2412LC.Alpha;
Cl = W2412LC.Cl;
figure()
hold on;
plot (Alpha,Cl,'LineWidth',1.5)
xL = xlim
yL = ylim;
xticks(-20:10:xL(2));
yticks(yL(1):0.5:yL(2));
xlim([-16 22])
title('Lift curve : NUM Elliptical Wing');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
hold off
%Drag Curve
Alpha = W2412DC.Alpha;
Cd = W2412DC.Cd;
figure()
hold on;
plot (Alpha,Cd,'LineWidth',1.5)
xL = xlim,
yL = ylim;
xticks(-20:5:20);
yticks(yL(1):0.02:yL(2));
xlim([-16 22])
title('Induced drag curve : NUM Elliptical Wing');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Induced drag coefficient :C_{d_i}');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
hold off

%% lift line 

Alpha = (W2412LC.Alpha);
Cl = W2412LC.Cl;
figure()
hold on;
plot (Alpha,Cl,'c','LineWidth',1.5)
Alpha = (W2412LC.Alpha +2.04);
plot (Alpha,Cl,'b','LineWidth',1.5)
xL = xlim;
yL = ylim;
x = [-50 50]
y = [0.341 0.341]
xticks(-20:10:xL(2));
yticks(yL(1):0.5:yL(2));
xlim([-16 22])
title('Lift curve : NUM Elliptical Wing');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
plot(x,y, 'r','LineWidth',1.5);   
[xout,yout] = intersections(x,y,Alpha,Cl);
plot(xout,yout,'k.','markersize',18)
hold off

Alpha = W2412DC.Alpha;
Cd = W2412DC.Cd;
figure()
hold on;
plot (Alpha,Cd,'c','LineWidth',1.5)
Alpha = (W2412DC.Alpha +2.04);
plot (Alpha,Cd,'b','LineWidth',1.5)
xL = xlim,
yL = ylim;
xticks(-20:5:20);
yticks(yL(1):0.02:yL(2));
xlim([-16 22])
ylim([0 0.15])
x = [3.01 3.01]
y = [50 -50]
title('Induced drag curve : NUM Elliptical Wing');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Induced drag coefficient :C_{d_i}');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
plot(x,y, 'r','LineWidth',1.5); 
[xout,yout] = intersections(x,y,Alpha,Cd);
plot(xout,yout,'k.','markersize',18)
hold off


