%% Import data from text file DP
% Script for importing data from the following text file:
%
%    filename: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\DP2412.csv
%
% Auto-generated by MATLAB on 01-Nov-2023 17:43:36

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Cl", "Cd"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
DP2421 = readtable(".\DP2421.csv", opts);
DP2418 = readtable(".\DP2418.csv", opts);
DP2415 = readtable(".\DP2415.csv", opts);
DP2412 = readtable(".\DP2412.csv", opts);
DP2409 = readtable(".\DP2409.csv", opts);
DP2406 = readtable(".\DP2406.csv", opts);
%Clear temporary variables
clear opts

%% Import data from text file LC2412
% Script for importing data from the following text file:
%
%    filename: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\LC2412.csv
%
% Auto-generated by MATLAB on 01-Nov-2023 17:44:40

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Alpha", "Cl_a"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
LC2421 = readtable(".\LC2421.csv", opts);
LC2418 = readtable(".\LC2418.csv", opts);
LC2415 = readtable(".\LC2415.csv", opts);
LC2412 = readtable(".\LC2412.csv", opts);
LC2409 = readtable(".\LC2409.csv", opts);
LC2406 = readtable(".\LC2406.csv", opts);
% Clear temporary variables
clear opts

%% Import data from spreadsheet EXP
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\selim\Documents\HKUST BA5\Aerodynamics\Project\XFLR 5 Results\Experimental Data.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 01-Nov-2023 18:47:55

% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 29);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A1:AC30";

% Specify column names and types
opts.VariableNames = ["Alpha", "NACA2406", "NACA2406D", "NACA2406tripped", "NACA2406trippedD", "NACA2409", "NACA2409D", "NACA2409tripped", "NACA2409trippedD", "NACA2412", "NACA2412D", "NACA2412tripped", "NACA2412trippedD", "NACA2415", "NACA2415D", "NACA2415tripped", "NACA2415trippedD", "NACA2418", "NACA2418D", "NACA2418tripped", "NACA2418trippedD", "NACA2421", "NACA2421D", "NACA2421tripped", "NACA2421trippedD", "NACA1412", "NACA1412D", "NACA3412", "NACA3412D"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ExperimentalData = readtable(".\Experimental Data.xlsx", opts, "UseExcel", false);

%Clear temporary variables
clear opts

%% Plots NUM
%Lift curve
Alpha = LC2406.Alpha;
Cl_a = LC2406.Cl_a;
figure()
plot (Alpha,Cl_a,'LineWidth',1.5)
hold on;
xticks(-20:10:20);
yticks(-2:0.5:2.5);
title('Lift curve : NUM Thickness Analysis');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
yline(0, 'k','LineStyle','--','LineWidth',0.25);   %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis
%2409
Alpha = LC2409.Alpha;
Cl_a = LC2409.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2412
Alpha = LC2412.Alpha;
Cl_a = LC2412.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2415
Alpha = LC2415.Alpha;
Cl_a = LC2415.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2418
Alpha = LC2418.Alpha;
Cl_a = LC2418.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
%2421
Alpha = LC2421.Alpha;
Cl_a = LC2421.Cl_a;
plot (Alpha,Cl_a,'LineWidth',1.5)
legend('2406','','', '2409', '2412', '2415', '2418', '2421', 'Location', 'southeast')
hold off

%Drag Polar
figure()
Cl=DP2406.Cl;
Cd=DP2406.Cd;
plot (Cl,Cd,'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):0.5:xL(2));
yticks(yL(1):0.02:yL(2));
title('Drag polar : NUM Thickness Anaysis');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);   %y-axis 
%2409
Cl=DP2409.Cl;
Cd=DP2409.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2412
Cl=DP2412.Cl;
Cd=DP2412.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2415
Cl=DP2415.Cl;
Cd=DP2415.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2418
Cl=DP2418.Cl;
Cd=DP2418.Cd;
plot (Cl,Cd,'LineWidth',1.5)
%2421
Cl=DP2421.Cl;
Cd=DP2421.Cd;
plot (Cl,Cd,'LineWidth',1.5)
legend('2406','', '2409', '2412', '2415', '2418', '2421')
hold off;

%% Plots EXP
%Lift Curve
Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2406)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Alpha,Cl_a,'LineWidth',1.5)
hold on;
xL = xlim;
yL = ylim;
xticks(xL(1):10:xL(2));
yticks(-1:0.5:1.5);
title('Lift curve : EXP Thickness Analysis');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_L');
yline(0, 'k','LineStyle','--','LineWidth',0.25);  %x-axis
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis


Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2409)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2412)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2415)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2418)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)

Alpha = ExperimentalData.Alpha;
Cl_a = (ExperimentalData.NACA2421)./(0.5*0.395*0.1*23*23*1.1606);
plot (Alpha,Cl_a,'LineWidth',1.5)
hold off; 
legend('2406','','', '2409', '2412', '2415', '2418', '2421', 'Location', 'southeast')

%Drag Polar
Cl=(ExperimentalData.NACA2406)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2406D)./(0.5*0.395*0.1*23*23*1.1606);
figure()
plot (Cl,Cd,'LineWidth',1.5)
hold on;
yL = ylim;
xticks(-1:0.5:1.5);
yticks(yL(1):0.04:0.36);
title('Drag polar : EXP Thickness Analysis');
xlabel('Lift coefficient : C_l');
ylabel('Drag coefficient : C_d');
xline(0, 'k','LineStyle','--','LineWidth',0.25);  %y-axis

Cl=(ExperimentalData.NACA2409)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2409D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2412)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2412D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2415)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2415D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2418)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2418D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)

Cl=(ExperimentalData.NACA2421)./(0.5*0.395*0.1*23*23*1.1606);
Cd= (ExperimentalData.NACA2421D)./(0.5*0.395*0.1*23*23*1.1606);
plot (Cl,Cd,'LineWidth',1.5)
legend('2406','', '2409', '2412', '2415', '2418', '2421')
hold off;
%% Theoritical Approach
x = -20:0.01:20;
C_l= ((pi^2)/90)*(x + 2.077);
figure()
plot(x, C_l,'LineWidth', 1.5)
hold on;
xL = xlim;
yL = ylim;
plot([0 0], yL,'k','LineStyle','--','LineWidth',0.25);  %y-axis
plot(xL, [0 0], 'k','LineStyle','--','LineWidth',0.25);  %x-axis
xticks(xL(1):10:xL(2));
yticks(yL(1):0.5:yL(2));
title('Lift curve : TAT Thickness Analysis');
xlabel('Angle of attack : \alpha (in deg)');
ylabel('Lift coefficient : C_l ');
hold off






